exclude: ^(docs/|venv/|legacy/)
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: check-json
          - id: check-toml
          - id: check-merge-conflict
          - id: fix-encoding-pragma
            args: ["--remove"]
            exclude: "setup.py"
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
          - id: pyupgrade
            args: ["--py310-plus"]
            exclude: "setup.py"
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: ""
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 23.11.0
      hooks:
          - id: black
            additional_dependencies:
                - click>=8.0
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear>=23.12.0
            exclude: ^(docs/)
    - repo: https://github.com/codespell-project/codespell
      rev: v2.1.0
      hooks:
          - id: codespell
            exclude: ^(windows/)
